Resources:

  Ec2TurnONFunction:

    Type: 'AWS::Lambda::Function'

    Properties:

      FunctionName: Ec2TurnOFF

      Description: This function turns on the DR EC2 instance

      Handler: index.handler

      MemorySize: 2048

      Role:

        Ref: IAMRoleforLambda

      Runtime: python3.7

      Timeout: 10

      Code:

        ZipFile: |

          import boto3

          region = 'us-east-1'

          instances = ['i-i-081fc9a044eaa945d'] ## instance id of the DR EC2 ##

          ec2 = boto3.client('ec2', region_name=region)



          def lambda_handler(event, context):

              ec2.stop_instances(InstanceIds=instances)

              print('stopped your instances: ' + str(instances))