AWSTemplateFormatVersion: 2010-09-09

Parameters:

  RoleName:

    Type: String

Resources:

  RoleforLambda:

    Type: 'AWS::IAM::Role'

    Properties:

      RoleName:

        Ref: RoleName

      AssumeRolePolicyDocument:

        Statement:

          - Action: 'sts:AssumeRole'

            Effect: Allow

            Principal:

              Service: lambda.amazonaws.com

      Policies:

        - PolicyName: SplunkLambdaPermissions

          PolicyDocument:

            Statement:

              - Effect: Allow

                Action:

                  - 'logs:CreateLogGroup'

                  - 'logs:CreateLogStream'

                  - 'logs:PutLogEvents'

                  - 'ec2:Start*'

                  - 'ec2:Stop*'

                Resource: '*'
