AWSTemplateFormatVersion: 2010-09-09

Description: Template to turn on the DR splunk instance in case of DR

Parameters:

  IAMRoleforLambda:

    Type: String

    Description: Enter the IAM Role ARN created for Lambda

Resources:

  Ec2TurnONFunction:

    Type: 'AWS::Lambda::Function'

    Properties:

      FunctionName: Ec2TurnON

      Description: This function turns on the DR EC2 instance

      Handler: index.handler

      MemorySize: 2048

      Role:

        Ref: IAMRoleforLambda

      Runtime: python3.7

      Timeout: 10

      Code:

        ZipFile: |

          import boto3

          region = 'us-east-1'

          instances = ['i-i-081fc9a044eaa945d'] ## instance id of the DR EC2 ##

          ec2 = boto3.client('ec2', region_name=region)



          def lambda_handler(event, context):

              ec2.start_instances(InstanceIds=instances)

              print('started your instances: ' + str(instances))
