AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EmailAddress:
    Type: String
    

Resources:

  EC2ServiceDegradationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Sub 'EC2ServiceDegradation'
      
  Ec2serviceSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref EC2ServiceDegradationTopic
      Protocol: email
      Endpoint: !Ref EmailAddress ## Email address of intended users ##
      
  EventRule: 
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: "EventRuleforEc2ServiceDegaradation"
      EventPattern: 
        source: 
          - "aws.health"
        detail-type: 
          - "AWS Health Event"
        detail:
          service: 
            - "EC2"
          eventTypeCategory: 
            - "issue"
          state: 
            - "AWS_EC2_API_ISSUE"
            - "AWS_EC2_NETWORK_CONNECTIVITY_ISSUE"
            - "AWS_EC2_OPERATIONAL_ISSUE"
            - "AWS_EC2_POWER_CONNECTIVITY_ISSUE"
            - "AWS_EC2_INSTANCE_AUTO_RECOVERY_FAILURE"
            - "AWS_EC2_INSTANCE_STORE_DRIVE_PERFORMANCE_DEGRADED"
            
      Targets: 
        - Arn: !Ref EC2ServiceDegradationTopic
          Id: "EC2issue"